version: '3.8'

volumes:
  pg_data_kittygram:
  static_volume_kittygram:
  media_volume_kittygram:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_kittygram:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - kittygram_network

  backend:
    image: daviddockerunique/kittygram_backend
    env_file: .env
    volumes:
      - static_volume_kittygram:/backend_static
      - media_volume_kittygram:/app/media
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - kittygram_network

  frontend:
    image: daviddockerunique/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume_kittygram:/frontend_static
    networks:
      - kittygram_network

  gateway:
    image: daviddockerunique/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static_volume_kittygram:/staticfiles
      - media_volume_kittygram:/var/www/kittygram/media/
    depends_on:
      - backend
      - frontend
    networks:
      - kittygram_network

networks:
  kittygram_network:
    driver: bridge