# Generated by Django 5.1.1 on 2025-04-26 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comment_options_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_post',
            new_name='post',
        ),
    ]
