# Generated by Django 5.1.1 on 2025-03-23 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('pk',), 'verbose_name': 'публикация', 'verbose_name_plural': 'Публикации'},
        ),
    ]
