"""Add user relationship to Donation

Revision ID: e6a12ad42e56
Revises: de2de94e6ee9
Create Date: 2026-02-20 23:54:10.578440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6a12ad42e56'
down_revision: Union[str, None] = 'de2de94e6ee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_charityproject_name'), ['name'])

    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_donation_user_id_user'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_donation_user_id_user'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_charityproject_name'), type_='unique')

    # ### end Alembic commands ###
