# Generated by Django 5.1.1 on 2025-07-08 08:42

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('year', models.IntegerField(verbose_name='Год создания')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Произведение',
                'verbose_name_plural': 'Произведения',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'year'), name='unique_title_year'), models.CheckConstraint(condition=models.Q(('year__lte', django.db.models.functions.datetime.ExtractYear(django.db.models.functions.datetime.Now()))), name='year_not_future')],
            },
        ),
    ]
