# Generated by Django 5.1.1 on 2025-07-08 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='title',
            name='year_not_future',
        ),
    ]
